import { Technology, TechCategory } from "../types";

/**
 * Icon per category (display text lives in the i18n translations dictionary,
 * see src/i18n/translations.ts -> categories).
 */
export const CATEGORY_METADATA: Record<TechCategory, { icon: string }> = {
  frontend: { icon: "Layout" },
  backend: { icon: "Server" },
  mobile: { icon: "Smartphone" },
  database: { icon: "Database" },
  auth: { icon: "ShieldCheck" },
  cache: { icon: "Zap" },
  storage: { icon: "HardDrive" },
  payments: { icon: "CreditCard" },
  messaging: { icon: "Share2" },
  ai_llm: { icon: "Sparkles" },
  search: { icon: "Search" },
  monitoring: { icon: "Activity" },
  deployment: { icon: "Cloud" },
  cicd: { icon: "GitBranch" },
  communication: { icon: "Mail" },
};

export const TECH_CATALOG: Technology[] = [
  // --- FRONTEND ---
  {
    id: "react",
    name: "React",
    category: "frontend",
    tier: "client",
    tagline: { en: "Component-based UI library", fr: "Bibliothèque UI à base de composants" },
    description: {
      en: "Declarative, component-driven client-side SPA library.",
      fr: "Bibliothèque SPA côté client déclarative et orientée composants.",
    },
    badgeColor: "bg-cyan-500/10 text-cyan-600 border-cyan-200 dark:border-cyan-800 dark:text-cyan-400",
    accentColor: "#06b6d4",
    iconName: "Component",
    roleInArchitecture: "Single Page Application (SPA) client rendering interactive UI views in the browser.",
    defaultDeploymentZone: "Edge / CDN Network",
    supportedProtocols: ["HTTPS / REST", "GraphQL", "WebSocket"],
    typicalOutboundTo: ["backend", "auth", "monitoring"],
    bestFor: ["Interactive Dashboards", "Complex Web SPAs", "Rich Client Applications"],
    pricingModel: "Open Source",
    documentationUrl: "https://react.dev",
  },
  {
    id: "nextjs",
    name: "Next.js",
    category: "frontend",
    tier: "edge",
    tagline: { en: "Full-stack React & SSR framework", fr: "Framework React full-stack & SSR" },
    description: {
      en: "Hybrid server-side rendering, API routes, and edge runtime.",
      fr: "Rendu côté serveur hybride, routes API et runtime en périphérie (edge).",
    },
    badgeColor: "bg-neutral-500/10 text-neutral-700 border-neutral-300 dark:border-neutral-700 dark:text-neutral-300",
    accentColor: "#171717",
    iconName: "Globe",
    roleInArchitecture: "SSR / SSG frontend + Edge Server API Gateway layer.",
    defaultDeploymentZone: "Edge / CDN Network",
    supportedProtocols: ["HTTPS / REST", "GraphQL", "SDK / Internal RPC"],
    typicalOutboundTo: ["backend", "database", "auth", "cache", "ai_llm", "payments", "monitoring"],
    bestFor: ["SEO-Heavy Web Apps", "E-Commerce", "High Performance SaaS"],
    pricingModel: "Open Source",
    documentationUrl: "https://nextjs.org",
  },
  {
    id: "vue",
    name: "Vue.js",
    category: "frontend",
    tier: "client",
    tagline: { en: "Progressive JavaScript framework", fr: "Framework JavaScript progressif" },
    description: {
      en: "Intuitive, approachable reactive framework for web interfaces.",
      fr: "Framework réactif intuitif et accessible pour les interfaces web.",
    },
    badgeColor: "bg-emerald-500/10 text-emerald-600 border-emerald-200 dark:border-emerald-800 dark:text-emerald-400",
    accentColor: "#10b981",
    iconName: "Layers",
    roleInArchitecture: "Reactive client-side UI rendering layer.",
    defaultDeploymentZone: "Edge / CDN Network",
    supportedProtocols: ["HTTPS / REST", "GraphQL", "WebSocket"],
    typicalOutboundTo: ["backend", "auth", "monitoring"],
    bestFor: ["Fast UI prototyping", "Medium to large applications", "Enterprise dashboards"],
    pricingModel: "Open Source",
    documentationUrl: "https://vuejs.org",
  },
  {
    id: "nuxt",
    name: "Nuxt",
    category: "frontend",
    tier: "edge",
    tagline: { en: "SSR & Full-stack Vue framework", fr: "Framework Vue full-stack & SSR" },
    description: {
      en: "Intuitive Vue framework with server engine (Nitro) and SEO capabilities.",
      fr: "Framework Vue intuitif avec moteur serveur (Nitro) et fonctionnalités SEO.",
    },
    badgeColor: "bg-green-500/10 text-green-600 border-green-200 dark:border-green-800 dark:text-green-400",
    accentColor: "#22c55e",
    iconName: "Globe",
    roleInArchitecture: "SSR Vue application and edge route rendering.",
    defaultDeploymentZone: "Edge / CDN Network",
    supportedProtocols: ["HTTPS / REST", "GraphQL"],
    typicalOutboundTo: ["backend", "database", "auth", "cache"],
    bestFor: ["Vue-based SaaS", "Content Websites", "SEO platforms"],
    pricingModel: "Open Source",
    documentationUrl: "https://nuxt.com",
  },
  {
    id: "svelte",
    name: "Svelte",
    category: "frontend",
    tier: "client",
    tagline: { en: "Cybernetically enhanced web apps", fr: "Applications web cybernétiquement améliorées" },
    description: {
      en: "Compiler-based ultra-lightweight reactive framework with no virtual DOM.",
      fr: "Framework réactif ultra-léger basé sur un compilateur, sans DOM virtuel.",
    },
    badgeColor: "bg-orange-500/10 text-orange-600 border-orange-200 dark:border-orange-800 dark:text-orange-400",
    accentColor: "#f97316",
    iconName: "Flame",
    roleInArchitecture: "Zero-runtime client UI bundle.",
    defaultDeploymentZone: "Edge / CDN Network",
    supportedProtocols: ["HTTPS / REST", "GraphQL", "WebSocket"],
    typicalOutboundTo: ["backend", "auth", "monitoring"],
    bestFor: ["Low-latency UIs", "Embedded widgets", "Interactive tools"],
    pricingModel: "Open Source",
    documentationUrl: "https://svelte.dev",
  },
  {
    id: "sveltekit",
    name: "SvelteKit",
    category: "frontend",
    tier: "edge",
    tagline: { en: "Fullstack Svelte application framework", fr: "Framework d'application Svelte full-stack" },
    description: {
      en: "Fast fullstack framework powering Svelte applications with server endpoints.",
      fr: "Framework full-stack rapide alimentant les applications Svelte avec des points de terminaison serveur.",
    },
    badgeColor: "bg-rose-500/10 text-rose-600 border-rose-200 dark:border-rose-800 dark:text-rose-400",
    accentColor: "#f43f5e",
    iconName: "Zap",
    roleInArchitecture: "Fullstack edge frontend and server endpoint router.",
    defaultDeploymentZone: "Edge / CDN Network",
    supportedProtocols: ["HTTPS / REST", "GraphQL", "SQL / Wire Protocol"],
    typicalOutboundTo: ["backend", "database", "auth", "payments"],
    bestFor: ["Solo developers", "High-performance websites", "Lean SaaS"],
    pricingModel: "Open Source",
    documentationUrl: "https://kit.svelte.dev",
  },
  {
    id: "angular",
    name: "Angular",
    category: "frontend",
    tier: "client",
    tagline: { en: "Enterprise-grade web platform", fr: "Plateforme web de niveau entreprise" },
    description: {
      en: "Opinionated, feature-complete framework with built-in dependency injection.",
      fr: "Framework structuré et complet avec injection de dépendances intégrée.",
    },
    badgeColor: "bg-red-500/10 text-red-600 border-red-200 dark:border-red-800 dark:text-red-400",
    accentColor: "#ef4444",
    iconName: "Shield",
    roleInArchitecture: "Robust, structured client application layer.",
    defaultDeploymentZone: "Edge / CDN Network",
    supportedProtocols: ["HTTPS / REST", "gRPC", "WebSocket"],
    typicalOutboundTo: ["backend", "auth", "monitoring"],
    bestFor: ["Large Enterprise SPAs", "Banking & Finance apps", "Regulated portals"],
    pricingModel: "Open Source",
    documentationUrl: "https://angular.dev",
  },
  {
    id: "remix",
    name: "Remix",
    category: "frontend",
    tier: "edge",
    tagline: {
      en: "Full stack web framework focused on web standards",
      fr: "Framework web full-stack centré sur les standards du web",
    },
    description: {
      en: "Web-standards based framework leveraging browser caching and fast SSR.",
      fr: "Framework basé sur les standards du web tirant parti du cache navigateur et d'un SSR rapide.",
    },
    badgeColor: "bg-indigo-500/10 text-indigo-600 border-indigo-200 dark:border-indigo-800 dark:text-indigo-400",
    accentColor: "#6366f1",
    iconName: "Radio",
    roleInArchitecture: "Server-rendered React UI with progressive enhancement.",
    defaultDeploymentZone: "Edge / CDN Network",
    supportedProtocols: ["HTTPS / REST", "SQL / Wire Protocol"],
    typicalOutboundTo: ["backend", "database", "auth", "payments"],
    bestFor: ["Data-dense applications", "Fast transactional web apps"],
    pricingModel: "Open Source",
    documentationUrl: "https://remix.run",
  },
  {
    id: "astro",
    name: "Astro",
    category: "frontend",
    tier: "edge",
    tagline: { en: "Content-driven web framework", fr: "Framework web orienté contenu" },
    description: {
      en: "Zero-JS by default with island architecture for blazing fast static content.",
      fr: "Zéro JS par défaut avec une architecture en îlots pour un contenu statique ultra-rapide.",
    },
    badgeColor: "bg-purple-500/10 text-purple-600 border-purple-200 dark:border-purple-800 dark:text-purple-400",
    accentColor: "#a855f7",
    iconName: "Sparkles",
    roleInArchitecture: "High performance content portal and marketing site.",
    defaultDeploymentZone: "Edge / CDN Network",
    supportedProtocols: ["HTTPS / REST"],
    typicalOutboundTo: ["backend", "storage", "search"],
    bestFor: ["Documentation portals", "Content & Media sites", "Landing pages"],
    pricingModel: "Open Source",
    documentationUrl: "https://astro.build",
  },

  // --- BACKEND ---
  {
    id: "fastapi",
    name: "FastAPI",
    category: "backend",
    tier: "api",
    tagline: { en: "High-performance Python API framework", fr: "Framework API Python haute performance" },
    description: {
      en: "Asynchronous Python framework with automatic OpenAPI docs and type validation.",
      fr: "Framework Python asynchrone avec documentation OpenAPI automatique et validation de types.",
    },
    badgeColor: "bg-teal-500/10 text-teal-600 border-teal-200 dark:border-teal-800 dark:text-teal-400",
    accentColor: "#14b8a6",
    iconName: "Terminal",
    roleInArchitecture: "Core asynchronous API backend handling business logic and AI orchestration.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "WebSocket", "gRPC"],
    typicalOutboundTo: ["database", "cache", "storage", "payments", "ai_llm", "messaging", "monitoring", "communication"],
    bestFor: ["AI/ML Services", "Microservices", "High-throughput APIs", "Data Science Backends"],
    pricingModel: "Open Source",
    documentationUrl: "https://fastapi.tiangolo.com",
  },
  {
    id: "nestjs",
    name: "NestJS",
    category: "backend",
    tier: "api",
    tagline: { en: "Structured TypeScript enterprise framework", fr: "Framework TypeScript structuré pour l'entreprise" },
    description: {
      en: "Modular, architectural TypeScript framework built on top of Express/Fastify.",
      fr: "Framework TypeScript modulaire et architectural construit sur Express/Fastify.",
    },
    badgeColor: "bg-pink-500/10 text-pink-600 border-pink-200 dark:border-pink-800 dark:text-pink-400",
    accentColor: "#ec4899",
    iconName: "Cpu",
    roleInArchitecture: "Enterprise API server orchestrating services and microservice modules.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "GraphQL", "gRPC", "WebSocket", "AMQP / Kafka Protocol"],
    typicalOutboundTo: ["database", "cache", "storage", "payments", "messaging", "monitoring", "communication", "auth"],
    bestFor: ["Enterprise TypeScript Backends", "Domain-Driven Design", "Microservices"],
    pricingModel: "Open Source",
    documentationUrl: "https://nestjs.com",
  },
  {
    id: "express",
    name: "Express.js",
    category: "backend",
    tier: "api",
    tagline: { en: "Minimalist Node.js web server", fr: "Serveur web Node.js minimaliste" },
    description: {
      en: "Fast, unopinionated web framework for Node.js REST services.",
      fr: "Framework web rapide et sans parti pris pour services REST Node.js.",
    },
    badgeColor: "bg-amber-500/10 text-amber-600 border-amber-200 dark:border-amber-800 dark:text-amber-400",
    accentColor: "#f59e0b",
    iconName: "Server",
    roleInArchitecture: "REST API microservice and webhook ingestion endpoint.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "WebSocket"],
    typicalOutboundTo: ["database", "cache", "storage", "payments", "messaging", "monitoring"],
    bestFor: ["Lightweight APIs", "Microservices", "Node.js utilities"],
    pricingModel: "Open Source",
    documentationUrl: "https://expressjs.com",
  },
  {
    id: "django",
    name: "Django",
    category: "backend",
    tier: "api",
    tagline: { en: "Batteries-included Python framework", fr: "Framework Python tout compris" },
    description: {
      en: "Complete Python framework with built-in ORM, admin panel, and security modules.",
      fr: "Framework Python complet avec ORM intégré, panneau d'administration et modules de sécurité.",
    },
    badgeColor: "bg-emerald-600/10 text-emerald-700 border-emerald-300 dark:border-emerald-700 dark:text-emerald-400",
    accentColor: "#059669",
    iconName: "Box",
    roleInArchitecture: "Monolithic or REST API backend (via DRF) with robust ORM.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "GraphQL"],
    typicalOutboundTo: ["database", "cache", "storage", "payments", "messaging", "communication"],
    bestFor: ["Full-featured Web Applications", "Admin-Heavy SaaS", "Rapid MVP builds"],
    pricingModel: "Open Source",
    documentationUrl: "https://www.djangoproject.com",
  },
  {
    id: "laravel",
    name: "Laravel",
    category: "backend",
    tier: "api",
    tagline: { en: "Elegant PHP web artisan framework", fr: "Framework artisan PHP élégant" },
    description: {
      en: "Full-featured PHP framework with Eloquent ORM, queues, and artisan CLI.",
      fr: "Framework PHP complet avec ORM Eloquent, files d'attente et CLI artisan.",
    },
    badgeColor: "bg-red-500/10 text-red-600 border-red-200 dark:border-red-800 dark:text-red-400",
    accentColor: "#f43f5e",
    iconName: "Flame",
    roleInArchitecture: "Monolith or API backend managing application workflows and background jobs.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "WebSocket"],
    typicalOutboundTo: ["database", "cache", "storage", "payments", "messaging", "communication"],
    bestFor: ["SaaS startups", "E-commerce platforms", "Content management systems"],
    pricingModel: "Open Source",
    documentationUrl: "https://laravel.com",
  },
  {
    id: "springboot",
    name: "Spring Boot",
    category: "backend",
    tier: "api",
    tagline: { en: "Production-ready Java framework", fr: "Framework Java prêt pour la production" },
    description: {
      en: "Robust, resilient framework for enterprise Java / Kotlin microservices.",
      fr: "Framework robuste et résilient pour microservices Java / Kotlin d'entreprise.",
    },
    badgeColor: "bg-lime-500/10 text-lime-600 border-lime-200 dark:border-lime-800 dark:text-lime-400",
    accentColor: "#84cc16",
    iconName: "Shield",
    roleInArchitecture: "High-scale enterprise backend service and data transaction processor.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "gRPC", "AMQP / Kafka Protocol", "SQL / Wire Protocol"],
    typicalOutboundTo: ["database", "cache", "messaging", "monitoring", "auth"],
    bestFor: ["High-volume transactional systems", "Banking & Fintech", "Enterprise clouds"],
    pricingModel: "Open Source",
    documentationUrl: "https://spring.io/projects/spring-boot",
  },
  {
    id: "gin",
    name: "Go (Gin / Echo)",
    category: "backend",
    tier: "api",
    tagline: { en: "Ultra-fast compiled Go microservices", fr: "Microservices Go compilés ultra-rapides" },
    description: {
      en: "Lightweight, blazing-fast Go framework with minimal memory footprint.",
      fr: "Framework Go léger et ultra-rapide avec une empreinte mémoire minimale.",
    },
    badgeColor: "bg-sky-500/10 text-sky-600 border-sky-200 dark:border-sky-800 dark:text-sky-400",
    accentColor: "#0284c7",
    iconName: "Zap",
    roleInArchitecture: "High-throughput, low-latency microservice or real-time gateway.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "gRPC", "WebSocket", "TCP / Connection Pool"],
    typicalOutboundTo: ["database", "cache", "messaging", "monitoring"],
    bestFor: ["Real-time systems", "High-QPS APIs", "Edge proxies"],
    pricingModel: "Open Source",
    documentationUrl: "https://gin-gonic.com",
  },
  {
    id: "rails",
    name: "Ruby on Rails",
    category: "backend",
    tier: "api",
    tagline: {
      en: "Convention over configuration web framework",
      fr: "Framework web «convention plutôt que configuration»",
    },
    description: {
      en: "Productivity-focused framework with ActiveRecord and convention-first tooling.",
      fr: "Framework axé sur la productivité avec ActiveRecord et un outillage orienté convention.",
    },
    badgeColor: "bg-rose-600/10 text-rose-700 border-rose-300 dark:border-rose-700 dark:text-rose-400",
    accentColor: "#e11d48",
    iconName: "Gem",
    roleInArchitecture: "Rapid-development application backend and database orchestrator.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "WebSocket"],
    typicalOutboundTo: ["database", "cache", "storage", "payments", "messaging", "communication"],
    bestFor: ["Fast SaaS MVPs", "E-commerce stores", "Marketplaces"],
    pricingModel: "Open Source",
    documentationUrl: "https://rubyonrails.org",
  },

  // --- MOBILE ---
  {
    id: "reactnative",
    name: "React Native / Expo",
    category: "mobile",
    tier: "client",
    tagline: { en: "Cross-platform iOS & Android with React", fr: "iOS & Android multiplateforme avec React" },
    description: {
      en: "Native mobile apps built with React and JavaScript/TypeScript.",
      fr: "Applications mobiles natives construites avec React et JavaScript/TypeScript.",
    },
    badgeColor: "bg-cyan-500/10 text-cyan-600 border-cyan-200 dark:border-cyan-800 dark:text-cyan-400",
    accentColor: "#06b6d4",
    iconName: "Smartphone",
    roleInArchitecture: "Mobile client application running on user iOS and Android devices.",
    defaultDeploymentZone: "Client Device / User Tier",
    supportedProtocols: ["HTTPS / REST", "GraphQL", "WebSocket"],
    typicalOutboundTo: ["backend", "auth", "monitoring", "storage"],
    bestFor: ["Cross-platform mobile apps", "SaaS mobile companion apps", "Consumer apps"],
    pricingModel: "Open Source",
    documentationUrl: "https://reactnative.dev",
  },
  {
    id: "flutter",
    name: "Flutter",
    category: "mobile",
    tier: "client",
    tagline: {
      en: "Google's UI toolkit for natively compiled apps",
      fr: "Le kit UI de Google pour applications nativement compilées",
    },
    description: {
      en: "High-performance multiplatform UI toolkit powered by Dart.",
      fr: "Kit UI multiplateforme haute performance propulsé par Dart.",
    },
    badgeColor: "bg-blue-500/10 text-blue-600 border-blue-200 dark:border-blue-800 dark:text-blue-400",
    accentColor: "#3b82f6",
    iconName: "Smartphone",
    roleInArchitecture: "High-FPS native mobile & desktop client application.",
    defaultDeploymentZone: "Client Device / User Tier",
    supportedProtocols: ["HTTPS / REST", "gRPC", "WebSocket"],
    typicalOutboundTo: ["backend", "auth", "monitoring"],
    bestFor: ["Custom animations", "Fluid mobile experiences", "Unified multiplatform"],
    pricingModel: "Open Source",
    documentationUrl: "https://flutter.dev",
  },
  {
    id: "swift",
    name: "Swift / iOS Native",
    category: "mobile",
    tier: "client",
    tagline: { en: "Native Apple iOS & iPadOS apps", fr: "Applications iOS & iPadOS natives Apple" },
    description: {
      en: "First-party Swift & SwiftUI development for maximum iOS performance.",
      fr: "Développement natif Swift & SwiftUI pour une performance iOS maximale.",
    },
    badgeColor: "bg-amber-600/10 text-amber-700 border-amber-300 dark:border-amber-700 dark:text-amber-400",
    accentColor: "#d97706",
    iconName: "Smartphone",
    roleInArchitecture: "Native iOS client utilizing Apple hardware features.",
    defaultDeploymentZone: "Client Device / User Tier",
    supportedProtocols: ["HTTPS / REST", "gRPC", "WebSocket"],
    typicalOutboundTo: ["backend", "auth", "monitoring"],
    bestFor: ["Apple ecosystem apps", "High performance graphics & AR", "Native iOS SaaS"],
    pricingModel: "Open Source",
    documentationUrl: "https://developer.apple.com/swift/",
  },
  {
    id: "kotlin",
    name: "Kotlin / Android Native",
    category: "mobile",
    tier: "client",
    tagline: { en: "Native Android & Jetpack Compose apps", fr: "Applications Android natives & Jetpack Compose" },
    description: {
      en: "First-party Kotlin development for native Android devices.",
      fr: "Développement natif Kotlin pour appareils Android natifs.",
    },
    badgeColor: "bg-violet-500/10 text-violet-600 border-violet-200 dark:border-violet-800 dark:text-violet-400",
    accentColor: "#8b5cf6",
    iconName: "Smartphone",
    roleInArchitecture: "Native Android client utilizing Jetpack Compose.",
    defaultDeploymentZone: "Client Device / User Tier",
    supportedProtocols: ["HTTPS / REST", "gRPC", "WebSocket"],
    typicalOutboundTo: ["backend", "auth", "monitoring"],
    bestFor: ["Native Android experiences", "Hardware integration", "Enterprise Android"],
    pricingModel: "Open Source",
    documentationUrl: "https://kotlinlang.org",
  },

  // --- DATABASE ---
  {
    id: "postgresql",
    name: "PostgreSQL",
    category: "database",
    tier: "data",
    tagline: {
      en: "World's most advanced open source relational DB",
      fr: "La base de données relationnelle open source la plus avancée au monde",
    },
    description: {
      en: "ACID-compliant relational database with JSONB, extensions, and spatial support.",
      fr: "Base de données relationnelle conforme ACID avec JSONB, extensions et support spatial.",
    },
    badgeColor: "bg-sky-600/10 text-sky-700 border-sky-300 dark:border-sky-700 dark:text-sky-400",
    accentColor: "#0369a1",
    iconName: "Database",
    roleInArchitecture: "Primary transactional data store for structured domain entities and relations.",
    defaultDeploymentZone: "Managed Cloud Data",
    supportedProtocols: ["SQL / Wire Protocol", "TCP / Connection Pool"],
    typicalOutboundTo: [],
    bestFor: ["Core transactional data", "Complex querying", "SaaS multi-tenancy", "ACID guarantees"],
    pricingModel: "Open Source",
    documentationUrl: "https://www.postgresql.org",
  },
  {
    id: "supabase_db",
    name: "Supabase (Postgres BaaS)",
    category: "database",
    tier: "data",
    tagline: {
      en: "Open source Firebase alternative with Postgres",
      fr: "Alternative open source à Firebase basée sur Postgres",
    },
    description: {
      en: "Hosted PostgreSQL with instant REST/GraphQL APIs, Auth, Realtime, and Edge functions.",
      fr: "PostgreSQL hébergé avec API REST/GraphQL instantanées, Auth, temps réel et fonctions Edge.",
    },
    badgeColor: "bg-emerald-500/10 text-emerald-600 border-emerald-200 dark:border-emerald-800 dark:text-emerald-400",
    accentColor: "#10b981",
    iconName: "Database",
    roleInArchitecture: "Managed Backend-as-a-Service and real-time database.",
    defaultDeploymentZone: "Managed Cloud Data",
    supportedProtocols: ["HTTPS / REST", "SQL / Wire Protocol", "WebSocket"],
    typicalOutboundTo: ["storage", "auth"],
    bestFor: ["Fast MVP launches", "Real-time subscriptions", "Postgres-first SaaS"],
    pricingModel: "Freemium",
    documentationUrl: "https://supabase.com",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    category: "database",
    tier: "data",
    tagline: { en: "Document-oriented NoSQL database", fr: "Base de données NoSQL orientée documents" },
    description: {
      en: "Flexible JSON-like document store designed for high agility and horizontal scale.",
      fr: "Stockage de documents flexible façon JSON, conçu pour une grande agilité et une scalabilité horizontale.",
    },
    badgeColor: "bg-green-600/10 text-green-700 border-green-300 dark:border-green-700 dark:text-green-400",
    accentColor: "#16a34a",
    iconName: "FileText",
    roleInArchitecture: "Document store for polymorphic, nested, or evolving schema data.",
    defaultDeploymentZone: "Managed Cloud Data",
    supportedProtocols: ["TCP / Connection Pool"],
    typicalOutboundTo: [],
    bestFor: ["Catalog management", "Event logging", "Dynamic schema applications"],
    pricingModel: "Open Source",
    documentationUrl: "https://www.mongodb.com",
  },
  {
    id: "mysql",
    name: "MySQL",
    category: "database",
    tier: "data",
    tagline: { en: "Proven open source relational database", fr: "Base de données relationnelle open source éprouvée" },
    description: {
      en: "Widely deployed relational DBMS powering web systems worldwide.",
      fr: "SGBD relationnel largement déployé propulsant des systèmes web dans le monde entier.",
    },
    badgeColor: "bg-blue-600/10 text-blue-700 border-blue-300 dark:border-blue-700 dark:text-blue-400",
    accentColor: "#2563eb",
    iconName: "Database",
    roleInArchitecture: "Primary relational data store for structured transactions.",
    defaultDeploymentZone: "Managed Cloud Data",
    supportedProtocols: ["SQL / Wire Protocol", "TCP / Connection Pool"],
    typicalOutboundTo: [],
    bestFor: ["Web portals", "E-commerce stores", "Standard relational schemas"],
    pricingModel: "Open Source",
    documentationUrl: "https://www.mysql.com",
  },
  {
    id: "redis_db",
    name: "Redis (Data Store)",
    category: "database",
    tier: "data",
    tagline: { en: "In-memory data structure store", fr: "Store de structures de données en mémoire" },
    description: {
      en: "Ultra-fast in-memory store supporting strings, hashes, sets, sorted sets, and streams.",
      fr: "Store en mémoire ultra-rapide prenant en charge chaînes, hachages, ensembles, ensembles triés et flux.",
    },
    badgeColor: "bg-red-500/10 text-red-600 border-red-200 dark:border-red-800 dark:text-red-400",
    accentColor: "#dc2626",
    iconName: "Zap",
    roleInArchitecture: "In-memory fast key-value lookup and ephemeral data persistence.",
    defaultDeploymentZone: "Managed Cloud Data",
    supportedProtocols: ["Redis Protocol (RESP)"],
    typicalOutboundTo: [],
    bestFor: ["Leaderboards", "Counters", "Session states", "Rate limiting"],
    pricingModel: "Open Source",
    documentationUrl: "https://redis.io",
  },
  {
    id: "sqlite",
    name: "SQLite / Turso",
    category: "database",
    tier: "data",
    tagline: {
      en: "Embedded or distributed edge SQL database",
      fr: "Base de données SQL embarquée ou distribuée en périphérie",
    },
    description: {
      en: "Self-contained serverless SQL engine, easily replicated to the edge with Turso/libSQL.",
      fr: "Moteur SQL serverless autonome, facilement répliqué en périphérie avec Turso/libSQL.",
    },
    badgeColor: "bg-slate-500/10 text-slate-700 border-slate-300 dark:border-slate-700 dark:text-slate-400",
    accentColor: "#64748b",
    iconName: "Database",
    roleInArchitecture: "Embedded local DB or low-latency distributed edge SQL store.",
    defaultDeploymentZone: "Edge / CDN Network",
    supportedProtocols: ["SQL / Wire Protocol", "HTTPS / REST"],
    typicalOutboundTo: [],
    bestFor: ["Edge databases", "Local-first apps", "Single-node lightweight tools"],
    pricingModel: "Open Source",
    documentationUrl: "https://turso.tech",
  },
  {
    id: "dynamodb",
    name: "Amazon DynamoDB",
    category: "database",
    tier: "data",
    tagline: {
      en: "Fully managed serverless key-value NoSQL DB",
      fr: "Base NoSQL clé-valeur serverless entièrement managée",
    },
    description: {
      en: "Predictable single-digit millisecond latency at any scale with automated replication.",
      fr: "Latence prévisible de quelques millisecondes à toute échelle avec réplication automatisée.",
    },
    badgeColor: "bg-indigo-600/10 text-indigo-700 border-indigo-300 dark:border-indigo-700 dark:text-indigo-400",
    accentColor: "#4f46e5",
    iconName: "Database",
    roleInArchitecture: "Serverless, high-throughput NoSQL database with auto-scaling.",
    defaultDeploymentZone: "Managed Cloud Data",
    supportedProtocols: ["HTTPS / REST", "SDK / Internal RPC"],
    typicalOutboundTo: [],
    bestFor: ["Serverless backends", "High-concurrency workloads", "AWS architectures"],
    pricingModel: "Cloud Resource",
    documentationUrl: "https://aws.amazon.com/dynamodb/",
  },

  // --- AUTHENTICATION ---
  {
    id: "clerk",
    name: "Clerk",
    category: "auth",
    tier: "external",
    tagline: {
      en: "Complete User Management & Auth platform",
      fr: "Plateforme complète de gestion des utilisateurs & d'authentification",
    },
    description: {
      en: "Drop-in authentication, user profiles, organization multi-tenancy, and prebuilt UI components.",
      fr: "Authentification clé en main, profils utilisateurs, multi-tenant organisationnel et composants UI prêts à l'emploi.",
    },
    badgeColor: "bg-purple-500/10 text-purple-600 border-purple-200 dark:border-purple-800 dark:text-purple-400",
    accentColor: "#9333ea",
    iconName: "UserCheck",
    roleInArchitecture: "Identity provider managing user authentication, sessions, and multi-tenant org permissions.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["HTTPS / REST", "OIDC / OAuth 2.0", "Webhook (HTTPS POST)"],
    typicalOutboundTo: ["backend"],
    bestFor: ["B2B SaaS with Organizations", "Next.js/React applications", "Fast auth setup"],
    pricingModel: "Freemium",
    documentationUrl: "https://clerk.com",
  },
  {
    id: "auth0",
    name: "Auth0 / Okta",
    category: "auth",
    tier: "external",
    tagline: { en: "Enterprise identity and SSO platform", fr: "Plateforme d'identité et de SSO d'entreprise" },
    description: {
      en: "Standardized enterprise identity provider supporting SAML, SSO, MFA, and social logins.",
      fr: "Fournisseur d'identité d'entreprise standardisé prenant en charge SAML, SSO, MFA et connexions sociales.",
    },
    badgeColor: "bg-orange-500/10 text-orange-600 border-orange-200 dark:border-orange-800 dark:text-orange-400",
    accentColor: "#ea580c",
    iconName: "Shield",
    roleInArchitecture: "Enterprise SSO and OIDC authentication service.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["OIDC / OAuth 2.0", "HTTPS / REST", "Webhook (HTTPS POST)"],
    typicalOutboundTo: ["backend"],
    bestFor: ["Enterprise SSO / SAML", "Regulated compliance", "Complex IAM architectures"],
    pricingModel: "Managed SaaS",
    documentationUrl: "https://auth0.com",
  },
  {
    id: "supabase_auth",
    name: "Supabase Auth",
    category: "auth",
    tier: "external",
    tagline: {
      en: "Row-Level Security powered auth for Postgres",
      fr: "Authentification pour Postgres propulsée par la sécurité au niveau des lignes",
    },
    description: {
      en: "Integrated identity provider tightly coupled with PostgreSQL Row Level Security (RLS).",
      fr: "Fournisseur d'identité intégré, étroitement couplé à la sécurité au niveau des lignes (RLS) de PostgreSQL.",
    },
    badgeColor: "bg-emerald-500/10 text-emerald-600 border-emerald-200 dark:border-emerald-800 dark:text-emerald-400",
    accentColor: "#10b981",
    iconName: "Key",
    roleInArchitecture: "User authentication gateway verifying tokens directly against database RLS policies.",
    defaultDeploymentZone: "Managed Cloud Data",
    supportedProtocols: ["HTTPS / REST", "OIDC / OAuth 2.0"],
    typicalOutboundTo: ["database"],
    bestFor: ["Supabase ecosystems", "Row-Level Security apps", "Mobile & Web auth"],
    pricingModel: "Freemium",
    documentationUrl: "https://supabase.com/docs/guides/auth",
  },
  {
    id: "firebase_auth",
    name: "Firebase Auth",
    category: "auth",
    tier: "external",
    tagline: { en: "Google-backed simple identity provider", fr: "Fournisseur d'identité simple soutenu par Google" },
    description: {
      en: "Battle-tested authentication supporting email, phone SMS, and federated social providers.",
      fr: "Authentification éprouvée prenant en charge l'email, le SMS et les fournisseurs sociaux fédérés.",
    },
    badgeColor: "bg-yellow-500/10 text-yellow-600 border-yellow-200 dark:border-yellow-800 dark:text-yellow-400",
    accentColor: "#eab308",
    iconName: "Flame",
    roleInArchitecture: "Client-side identity management and JWT token generator.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["HTTPS / REST", "OIDC / OAuth 2.0"],
    typicalOutboundTo: ["backend"],
    bestFor: ["Mobile apps (Flutter/React Native)", "Rapid prototypes", "Google cloud integration"],
    pricingModel: "Freemium",
    documentationUrl: "https://firebase.google.com/products/auth",
  },
  {
    id: "nextauth",
    name: "Auth.js / NextAuth",
    category: "auth",
    tier: "api",
    tagline: {
      en: "Open-source self-hosted auth library for TypeScript",
      fr: "Bibliothèque d'authentification open source auto-hébergée pour TypeScript",
    },
    description: {
      en: "Lightweight authentication library keeping complete ownership over user database tables.",
      fr: "Bibliothèque d'authentification légère conservant une propriété complète des tables utilisateur en base de données.",
    },
    badgeColor: "bg-stone-500/10 text-stone-700 border-stone-300 dark:border-stone-700 dark:text-stone-300",
    accentColor: "#78716c",
    iconName: "Lock",
    roleInArchitecture: "In-process authentication middleware managing session cookies and OAuth callbacks.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "OIDC / OAuth 2.0", "SQL / Wire Protocol"],
    typicalOutboundTo: ["database"],
    bestFor: ["Data sovereignty", "Custom DB auth schemas", "Cost-free authentication"],
    pricingModel: "Open Source",
    documentationUrl: "https://authjs.dev",
  },

  // --- CACHE ---
  {
    id: "redis",
    name: "Redis Cache",
    category: "cache",
    tier: "cache",
    tagline: {
      en: "Sub-millisecond latency cache & session store",
      fr: "Cache & store de session à latence sub-milliseconde",
    },
    description: {
      en: "In-memory cache caching DB queries, session tokens, and rate-limiting counters.",
      fr: "Cache en mémoire mettant en cache les requêtes BD, jetons de session et compteurs de limitation de débit.",
    },
    badgeColor: "bg-red-500/10 text-red-600 border-red-200 dark:border-red-800 dark:text-red-400",
    accentColor: "#ef4444",
    iconName: "Zap",
    roleInArchitecture: "High-speed in-memory caching tier relieving database read load.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["Redis Protocol (RESP)"],
    typicalOutboundTo: [],
    bestFor: ["Query response caching", "Session persistence", "Rate limiting", "Real-time state"],
    pricingModel: "Open Source",
    documentationUrl: "https://redis.io",
  },
  {
    id: "dragonfly",
    name: "Dragonfly",
    category: "cache",
    tier: "cache",
    tagline: { en: "Modern multi-threaded Redis replacement", fr: "Remplaçant moderne multi-thread de Redis" },
    description: {
      en: "Highly scalable in-memory store yielding 25x Redis throughput with zero code changes.",
      fr: "Store en mémoire hautement scalable offrant un débit 25x supérieur à Redis sans changement de code.",
    },
    badgeColor: "bg-amber-500/10 text-amber-600 border-amber-200 dark:border-amber-800 dark:text-amber-400",
    accentColor: "#f59e0b",
    iconName: "Cpu",
    roleInArchitecture: "Multi-threaded cache cluster supporting high-QPS workloads.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["Redis Protocol (RESP)"],
    typicalOutboundTo: [],
    bestFor: ["Extreme traffic spikes", "Multi-core hardware efficiency", "Massive memory cache"],
    pricingModel: "Open Source",
    documentationUrl: "https://dragonflydb.io",
  },
  {
    id: "cloudflare_kv",
    name: "Cloudflare Workers KV",
    category: "cache",
    tier: "edge",
    tagline: {
      en: "Globally distributed low-latency key-value store",
      fr: "Store clé-valeur à faible latence distribué mondialement",
    },
    description: {
      en: "Edge-replicated key-value store providing single-digit millisecond reads worldwide.",
      fr: "Store clé-valeur répliqué en périphérie offrant des lectures de quelques millisecondes dans le monde entier.",
    },
    badgeColor: "bg-orange-500/10 text-orange-600 border-orange-200 dark:border-orange-800 dark:text-orange-400",
    accentColor: "#f97316",
    iconName: "Globe",
    roleInArchitecture: "Global edge caching for static assets, feature flags, and auth configs.",
    defaultDeploymentZone: "Edge / CDN Network",
    supportedProtocols: ["HTTPS / REST"],
    typicalOutboundTo: [],
    bestFor: ["Edge configuration", "Feature flags", "Static API caching"],
    pricingModel: "Freemium",
    documentationUrl: "https://developers.cloudflare.com/kv/",
  },

  // --- STORAGE ---
  {
    id: "s3",
    name: "AWS S3",
    category: "storage",
    tier: "external",
    tagline: { en: "Industry-standard object storage", fr: "Stockage objet standard de l'industrie" },
    description: {
      en: "Highly durable (99.999999999%) cloud storage for images, videos, documents, and backups.",
      fr: "Stockage cloud hautement durable (99,999999999 %) pour images, vidéos, documents et sauvegardes.",
    },
    badgeColor: "bg-orange-500/10 text-orange-600 border-orange-200 dark:border-orange-800 dark:text-orange-400",
    accentColor: "#f97316",
    iconName: "HardDrive",
    roleInArchitecture: "Central object storage repository with presigned URLs for client uploads.",
    defaultDeploymentZone: "Managed Cloud Data",
    supportedProtocols: ["Signed HTTPS / S3 API"],
    typicalOutboundTo: [],
    bestFor: ["Media storage", "Presigned direct client uploads", "Data lakes", "Disaster recovery"],
    pricingModel: "Cloud Resource",
    documentationUrl: "https://aws.amazon.com/s3/",
  },
  {
    id: "cloudflare_r2",
    name: "Cloudflare R2",
    category: "storage",
    tier: "external",
    tagline: {
      en: "Zero-egress fee S3-compatible storage",
      fr: "Stockage compatible S3 sans frais de sortie (egress)",
    },
    description: {
      en: "S3-compatible object storage eliminating data egress fees across global edge locations.",
      fr: "Stockage objet compatible S3 éliminant les frais de sortie de données sur les emplacements périphériques mondiaux.",
    },
    badgeColor: "bg-amber-500/10 text-amber-600 border-amber-200 dark:border-amber-800 dark:text-amber-400",
    accentColor: "#d97706",
    iconName: "HardDrive",
    roleInArchitecture: "Edge-distributed object storage with zero egress bandwidth charges.",
    defaultDeploymentZone: "Managed Cloud Data",
    supportedProtocols: ["Signed HTTPS / S3 API"],
    typicalOutboundTo: [],
    bestFor: ["High-download media sites", "Cost optimization", "S3 drop-in replacement"],
    pricingModel: "Freemium",
    documentationUrl: "https://developers.cloudflare.com/r2/",
  },
  {
    id: "gcs",
    name: "Google Cloud Storage",
    category: "storage",
    tier: "external",
    tagline: {
      en: "Secure, durable Google Cloud object storage",
      fr: "Stockage objet Google Cloud sécurisé et durable",
    },
    description: {
      en: "Object storage integrated seamlessly with GCP AI pipelines and BigQuery.",
      fr: "Stockage objet intégré de façon transparente aux pipelines IA GCP et à BigQuery.",
    },
    badgeColor: "bg-blue-500/10 text-blue-600 border-blue-200 dark:border-blue-800 dark:text-blue-400",
    accentColor: "#3b82f6",
    iconName: "HardDrive",
    roleInArchitecture: "GCP media store and AI dataset storage layer.",
    defaultDeploymentZone: "Managed Cloud Data",
    supportedProtocols: ["Signed HTTPS / S3 API", "HTTPS / REST"],
    typicalOutboundTo: [],
    bestFor: ["GCP native architectures", "BigQuery exports", "AI pipeline inputs"],
    pricingModel: "Cloud Resource",
    documentationUrl: "https://cloud.google.com/storage",
  },

  // --- PAYMENTS ---
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    tier: "external",
    tagline: {
      en: "Global payment processing & billing infrastructure",
      fr: "Infrastructure mondiale de traitement des paiements & facturation",
    },
    description: {
      en: "Credit cards, Apple Pay, subscription billing, customer portals, and merchant payouts.",
      fr: "Cartes de crédit, Apple Pay, facturation par abonnement, portails clients et reversements marchands.",
    },
    badgeColor: "bg-indigo-500/10 text-indigo-600 border-indigo-200 dark:border-indigo-800 dark:text-indigo-400",
    accentColor: "#6366f1",
    iconName: "CreditCard",
    roleInArchitecture: "Payment gateway processing checkout sessions and publishing payment webhook events.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["HTTPS / REST", "Webhook (HTTPS POST)"],
    typicalOutboundTo: ["backend"],
    bestFor: ["SaaS Subscriptions", "E-commerce Checkouts", "Global multi-currency billing"],
    pricingModel: "Managed SaaS",
    documentationUrl: "https://stripe.com",
  },
  {
    id: "lemonsqueezy",
    name: "Lemon Squeezy",
    category: "payments",
    tier: "external",
    tagline: {
      en: "Merchant of Record for software & digital goods",
      fr: "Marchand officiel (Merchant of Record) pour logiciels & biens numériques",
    },
    description: {
      en: "Handles global sales tax compliance, VAT, invoicing, and digital software checkouts.",
      fr: "Gère la conformité fiscale mondiale, la TVA, la facturation et les paiements de logiciels numériques.",
    },
    badgeColor: "bg-yellow-500/10 text-yellow-600 border-yellow-200 dark:border-yellow-800 dark:text-yellow-400",
    accentColor: "#ca8a04",
    iconName: "CreditCard",
    roleInArchitecture: "Merchant of Record simplifying international tax compliance and digital licensing.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["HTTPS / REST", "Webhook (HTTPS POST)"],
    typicalOutboundTo: ["backend"],
    bestFor: ["Solo Founders", "Digital products", "Automated global tax/VAT handling"],
    pricingModel: "Managed SaaS",
    documentationUrl: "https://lemonsqueezy.com",
  },

  // --- MESSAGING & ASYNC QUEUES ---
  {
    id: "rabbitmq",
    name: "RabbitMQ",
    category: "messaging",
    tier: "async",
    tagline: { en: "Reliable AMQP message broker", fr: "Broker de messages AMQP fiable" },
    description: {
      en: "Feature-rich message queue with routing keys, dead-letter exchanges, and worker consumers.",
      fr: "File de messages riche en fonctionnalités avec clés de routage, échanges de lettres mortes et workers consommateurs.",
    },
    badgeColor: "bg-orange-600/10 text-orange-700 border-orange-300 dark:border-orange-700 dark:text-orange-400",
    accentColor: "#ea580c",
    iconName: "Share2",
    roleInArchitecture: "Asynchronous task queue distributing heavy background jobs to worker pools.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["AMQP / Kafka Protocol", "HTTPS / REST"],
    typicalOutboundTo: [],
    bestFor: ["Background processing (Celery/BullMQ)", "Decoupled services", "Reliable delivery"],
    pricingModel: "Open Source",
    documentationUrl: "https://www.rabbitmq.com",
  },
  {
    id: "kafka",
    name: "Apache Kafka",
    category: "messaging",
    tier: "async",
    tagline: { en: "High-throughput distributed event streaming", fr: "Streaming d'événements distribué à haut débit" },
    description: {
      en: "Distributed commit log capable of processing millions of events per second with replayability.",
      fr: "Journal de transactions distribué capable de traiter des millions d'événements par seconde avec rejouabilité.",
    },
    badgeColor: "bg-slate-700/10 text-slate-800 border-slate-300 dark:border-slate-600 dark:text-slate-300",
    accentColor: "#334155",
    iconName: "Activity",
    roleInArchitecture: "Enterprise event streaming backbone for event-driven microservices.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["AMQP / Kafka Protocol"],
    typicalOutboundTo: [],
    bestFor: ["High-volume event streaming", "Audit trails", "Real-time analytics pipelines"],
    pricingModel: "Open Source",
    documentationUrl: "https://kafka.apache.org",
  },
  {
    id: "sqs",
    name: "AWS SQS & SNS",
    category: "messaging",
    tier: "async",
    tagline: {
      en: "Fully managed serverless queue and fanout",
      fr: "File d'attente et diffusion serverless entièrement managées",
    },
    description: {
      en: "Zero-maintenance message queues with DLQs and pub/sub topic fanout.",
      fr: "Files de messages sans maintenance avec files de lettres mortes (DLQ) et diffusion pub/sub par sujet.",
    },
    badgeColor: "bg-amber-600/10 text-amber-700 border-amber-300 dark:border-amber-700 dark:text-amber-400",
    accentColor: "#d97706",
    iconName: "Share2",
    roleInArchitecture: "Serverless async queue buffering webhook events and background tasks.",
    defaultDeploymentZone: "Managed Cloud Data",
    supportedProtocols: ["HTTPS / REST", "SDK / Internal RPC"],
    typicalOutboundTo: [],
    bestFor: ["Serverless event architectures", "AWS Lambda triggers", "Decoupled async workflows"],
    pricingModel: "Cloud Resource",
    documentationUrl: "https://aws.amazon.com/sqs/",
  },

  // --- AI / LLM ---
  {
    id: "gemini",
    name: "Google Gemini 3.0 / 2.5",
    category: "ai_llm",
    tier: "external",
    tagline: {
      en: "State-of-the-art multimodal AI foundation models",
      fr: "Modèles de fondation IA multimodaux à la pointe de la technologie",
    },
    description: {
      en: "Ultra-long context reasoning, multimodal image/audio/code processing, and function calling.",
      fr: "Raisonnement à très long contexte, traitement multimodal image/audio/code et appel de fonctions.",
    },
    badgeColor: "bg-blue-500/10 text-blue-600 border-blue-200 dark:border-blue-800 dark:text-blue-400",
    accentColor: "#2563eb",
    iconName: "Sparkles",
    roleInArchitecture: "AI Intelligence Engine performing reasoning, generation, embeddings, and tool orchestration.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["HTTPS / REST", "gRPC", "SDK / Internal RPC"],
    typicalOutboundTo: [],
    bestFor: ["Multimodal understanding", "Agentic workflows", "Long-document analysis", "Code generation"],
    pricingModel: "Managed SaaS",
    documentationUrl: "https://ai.google.dev",
  },
  {
    id: "openai",
    name: "OpenAI GPT-4o",
    category: "ai_llm",
    tier: "external",
    tagline: { en: "Industry standard LLM & embeddings API", fr: "API LLM & embeddings standard de l'industrie" },
    description: {
      en: "Powerful natural language models with structured JSON outputs and function calling.",
      fr: "Modèles de langage naturel puissants avec sorties JSON structurées et appel de fonctions.",
    },
    badgeColor: "bg-emerald-600/10 text-emerald-700 border-emerald-300 dark:border-emerald-700 dark:text-emerald-400",
    accentColor: "#059669",
    iconName: "Cpu",
    roleInArchitecture: "Large language model provider for text generation, embeddings, and chat completions.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["HTTPS / REST"],
    typicalOutboundTo: [],
    bestFor: ["Conversational agents", "Structured extraction", "Text transformation"],
    pricingModel: "Managed SaaS",
    documentationUrl: "https://platform.openai.com",
  },
  {
    id: "pinecone",
    name: "Pinecone / Vector DB",
    category: "ai_llm",
    tier: "data",
    tagline: {
      en: "Serverless vector database for RAG & semantic search",
      fr: "Base de données vectorielle serverless pour RAG & recherche sémantique",
    },
    description: {
      en: "High-performance vector index for semantic document search and similarity retrieval.",
      fr: "Index vectoriel haute performance pour la recherche sémantique de documents et la récupération par similarité.",
    },
    badgeColor: "bg-teal-500/10 text-teal-600 border-teal-200 dark:border-teal-800 dark:text-teal-400",
    accentColor: "#0d9488",
    iconName: "Database",
    roleInArchitecture: "Vector retrieval index providing context retrieval for LLM RAG pipelines.",
    defaultDeploymentZone: "Managed Cloud Data",
    supportedProtocols: ["HTTPS / REST", "gRPC"],
    typicalOutboundTo: [],
    bestFor: ["Retrieval-Augmented Generation (RAG)", "Semantic search", "Recommendation engines"],
    pricingModel: "Freemium",
    documentationUrl: "https://pinecone.io",
  },
  {
    id: "langchain",
    name: "LangChain / LlamaIndex",
    category: "ai_llm",
    tier: "api",
    tagline: {
      en: "Orchestration framework for AI agents and RAG",
      fr: "Framework d'orchestration pour agents IA et RAG",
    },
    description: {
      en: "Pipeline library chaining prompts, document chunking, embeddings, vector stores, and tools.",
      fr: "Bibliothèque de pipelines chaînant prompts, découpage de documents, embeddings, stores vectoriels et outils.",
    },
    badgeColor: "bg-cyan-600/10 text-cyan-700 border-cyan-300 dark:border-cyan-700 dark:text-cyan-400",
    accentColor: "#0891b2",
    iconName: "Layers",
    roleInArchitecture: "AI Orchestration layer running inside backend service managing prompt pipelines.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["SDK / Internal RPC"],
    typicalOutboundTo: ["ai_llm", "database"],
    bestFor: ["Complex AI agents", "Multi-step RAG workflows", "Document ingest pipelines"],
    pricingModel: "Open Source",
    documentationUrl: "https://langchain.com",
  },

  // --- SEARCH ---
  {
    id: "meilisearch",
    name: "Meilisearch",
    category: "search",
    tier: "data",
    tagline: {
      en: "Lightning-fast, typo-tolerant search engine",
      fr: "Moteur de recherche ultra-rapide et tolérant aux fautes",
    },
    description: {
      en: "Developer-friendly search engine with instant <50ms response times and smart filtering.",
      fr: "Moteur de recherche convivial pour développeurs avec des temps de réponse instantanés (<50 ms) et un filtrage intelligent.",
    },
    badgeColor: "bg-pink-500/10 text-pink-600 border-pink-200 dark:border-pink-800 dark:text-pink-400",
    accentColor: "#f43f5e",
    iconName: "Search",
    roleInArchitecture: "Dedicated search engine indexing application records for instant client search.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST"],
    typicalOutboundTo: [],
    bestFor: ["E-commerce product search", "SaaS dashboard search", "Fast autocomplete"],
    pricingModel: "Open Source",
    documentationUrl: "https://www.meilisearch.com",
  },
  {
    id: "elasticsearch",
    name: "Elasticsearch",
    category: "search",
    tier: "data",
    tagline: {
      en: "Distributed enterprise search & analytics engine",
      fr: "Moteur de recherche & analytique distribué d'entreprise",
    },
    description: {
      en: "Highly scalable Lucene-based search engine for big data search and log analytics.",
      fr: "Moteur de recherche basé sur Lucene, hautement scalable, pour la recherche big data et l'analyse de logs.",
    },
    badgeColor: "bg-blue-600/10 text-blue-700 border-blue-300 dark:border-blue-700 dark:text-blue-400",
    accentColor: "#2563eb",
    iconName: "Search",
    roleInArchitecture: "Enterprise distributed search index and analytical query store.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST"],
    typicalOutboundTo: [],
    bestFor: ["High-volume search catalogs", "Log aggregation", "Complex aggregations"],
    pricingModel: "Open Source",
    documentationUrl: "https://www.elastic.co",
  },
  {
    id: "algolia",
    name: "Algolia",
    category: "search",
    tier: "external",
    tagline: { en: "Hosted Search-as-a-Service API", fr: "API de recherche hébergée en tant que service" },
    description: {
      en: "Fully managed search API with instant UI libraries and analytics.",
      fr: "API de recherche entièrement managée avec bibliothèques UI instantanées et analytique.",
    },
    badgeColor: "bg-indigo-500/10 text-indigo-600 border-indigo-200 dark:border-indigo-800 dark:text-indigo-400",
    accentColor: "#4f46e5",
    iconName: "Search",
    roleInArchitecture: "Hosted search service with direct front-end query capabilities.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["HTTPS / REST"],
    typicalOutboundTo: [],
    bestFor: ["Turnkey front-end search", "E-commerce merchandising", "Zero-maintenance search"],
    pricingModel: "Freemium",
    documentationUrl: "https://www.algolia.com",
  },

  // --- MONITORING & OBSERVABILITY ---
  {
    id: "sentry",
    name: "Sentry",
    category: "monitoring",
    tier: "observability",
    tagline: {
      en: "Application performance monitoring & error tracking",
      fr: "Supervision de performance applicative & suivi des erreurs",
    },
    description: {
      en: "Real-time crash reporting with stack traces, breadcrumbs, release health, and tracing.",
      fr: "Rapports de plantage en temps réel avec traces de pile, breadcrumbs, santé des versions et tracing.",
    },
    badgeColor: "bg-rose-500/10 text-rose-600 border-rose-200 dark:border-rose-800 dark:text-rose-400",
    accentColor: "#e11d48",
    iconName: "AlertTriangle",
    roleInArchitecture: "Error monitoring SDK reporting client and backend runtime exceptions.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["HTTPS / REST"],
    typicalOutboundTo: [],
    bestFor: ["Crash reporting", "Frontend + Backend tracing", "Release stability"],
    pricingModel: "Freemium",
    documentationUrl: "https://sentry.io",
  },
  {
    id: "datadog",
    name: "Datadog",
    category: "monitoring",
    tier: "observability",
    tagline: {
      en: "Enterprise infrastructure & APM monitoring",
      fr: "Supervision d'infrastructure & APM d'entreprise",
    },
    description: {
      en: "Unified metrics, traces, server health, log management, and security monitoring.",
      fr: "Métriques, traces, santé serveur, gestion de logs et supervision de sécurité unifiées.",
    },
    badgeColor: "bg-purple-600/10 text-purple-700 border-purple-300 dark:border-purple-700 dark:text-purple-400",
    accentColor: "#7c3aed",
    iconName: "Activity",
    roleInArchitecture: "Comprehensive APM, container monitoring, and distributed tracing platform.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["OpenTelemetry / gRPC", "HTTPS / REST"],
    typicalOutboundTo: [],
    bestFor: ["Enterprise microservices", "Container fleet monitoring", "SLA alerting"],
    pricingModel: "Managed SaaS",
    documentationUrl: "https://www.datadoghq.com",
  },
  {
    id: "posthog",
    name: "PostHog",
    category: "monitoring",
    tier: "observability",
    tagline: {
      en: "Product analytics, session replay & feature flags",
      fr: "Analytique produit, relecture de session & feature flags",
    },
    description: {
      en: "All-in-one product analytics suite with funnels, session recordings, and A/B testing.",
      fr: "Suite d'analytique produit tout-en-un avec entonnoirs, enregistrements de session et tests A/B.",
    },
    badgeColor: "bg-amber-500/10 text-amber-600 border-amber-200 dark:border-amber-800 dark:text-amber-400",
    accentColor: "#f59e0b",
    iconName: "Activity",
    roleInArchitecture: "User analytics and telemetry tracking user events and feature flag evaluations.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["HTTPS / REST"],
    typicalOutboundTo: [],
    bestFor: ["Product growth analytics", "User session replays", "Feature flags"],
    pricingModel: "Freemium",
    documentationUrl: "https://posthog.com",
  },

  // --- DEPLOYMENT & HOSTING ---
  {
    id: "vercel",
    name: "Vercel",
    category: "deployment",
    tier: "infrastructure",
    tagline: {
      en: "Frontend cloud and serverless edge deployment",
      fr: "Cloud frontend et déploiement serverless en périphérie",
    },
    description: {
      en: "Automatic Git deployments, global edge network, serverless functions, and preview URLs.",
      fr: "Déploiements Git automatiques, réseau périphérique mondial, fonctions serverless et URLs de prévisualisation.",
    },
    badgeColor: "bg-neutral-600/10 text-neutral-800 border-neutral-300 dark:border-neutral-700 dark:text-neutral-300",
    accentColor: "#0a0a0a",
    iconName: "Triangle",
    roleInArchitecture: "Global edge CDN and serverless runtime hosting the web frontend.",
    defaultDeploymentZone: "Edge / CDN Network",
    supportedProtocols: ["HTTPS / REST"],
    typicalOutboundTo: ["backend", "database", "auth"],
    bestFor: ["Next.js/React frontend", "Edge APIs", "Instant preview deploys"],
    pricingModel: "Freemium",
    documentationUrl: "https://vercel.com",
  },
  {
    id: "gcp_cloudrun",
    name: "Google Cloud Run",
    category: "deployment",
    tier: "infrastructure",
    tagline: {
      en: "Fully managed serverless container platform",
      fr: "Plateforme de conteneurs serverless entièrement managée",
    },
    description: {
      en: "Run stateless containers that automatically scale from zero to thousands of instances.",
      fr: "Exécutez des conteneurs sans état qui s'adaptent automatiquement de zéro à des milliers d'instances.",
    },
    badgeColor: "bg-blue-500/10 text-blue-600 border-blue-200 dark:border-blue-800 dark:text-blue-400",
    accentColor: "#3b82f6",
    iconName: "Cloud",
    roleInArchitecture: "Container runtime hosting backend API services with zero-to-many auto-scaling.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "gRPC", "WebSocket"],
    typicalOutboundTo: ["database", "cache", "storage"],
    bestFor: ["Dockerized APIs (FastAPI/NestJS/Express)", "Scale-to-zero cost savings", "Production workloads"],
    pricingModel: "Cloud Resource",
    documentationUrl: "https://cloud.google.com/run",
  },
  {
    id: "aws_ecs",
    name: "AWS ECS / Fargate",
    category: "deployment",
    tier: "infrastructure",
    tagline: { en: "Serverless container orchestration on AWS", fr: "Orchestration de conteneurs serverless sur AWS" },
    description: {
      en: "Secure, highly reliable Docker container execution in private VPC subnets.",
      fr: "Exécution de conteneurs Docker sécurisée et hautement fiable dans des sous-réseaux VPC privés.",
    },
    badgeColor: "bg-orange-500/10 text-orange-600 border-orange-200 dark:border-orange-800 dark:text-orange-400",
    accentColor: "#f97316",
    iconName: "Cloud",
    roleInArchitecture: "Enterprise container cluster in VPC with fine-grained IAM roles.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "gRPC", "TCP / Connection Pool"],
    typicalOutboundTo: ["database", "cache", "storage", "messaging"],
    bestFor: ["Enterprise AWS backends", "Long-running workers", "Private VPC security"],
    pricingModel: "Cloud Resource",
    documentationUrl: "https://aws.amazon.com/ecs/",
  },
  {
    id: "railway",
    name: "Railway / Render",
    category: "deployment",
    tier: "infrastructure",
    tagline: {
      en: "Developer-first cloud platform for full-stack apps",
      fr: "Plateforme cloud orientée développeur pour applications full-stack",
    },
    description: {
      en: "Simple cloud hosting for web servers, cron jobs, and managed databases with zero DevOps.",
      fr: "Hébergement cloud simple pour serveurs web, tâches cron et bases de données managées, sans DevOps.",
    },
    badgeColor: "bg-purple-500/10 text-purple-600 border-purple-200 dark:border-purple-800 dark:text-purple-400",
    accentColor: "#a855f7",
    iconName: "Server",
    roleInArchitecture: "Application runtime hosting backend servers and worker processes.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "TCP / Connection Pool"],
    typicalOutboundTo: ["database", "cache"],
    bestFor: ["Indie hackers", "Startup MVPs", "Zero-config deployments"],
    pricingModel: "Freemium",
    documentationUrl: "https://railway.app",
  },
  {
    id: "kubernetes",
    name: "Kubernetes (K8s)",
    category: "deployment",
    tier: "infrastructure",
    tagline: { en: "Standard container orchestration platform", fr: "Plateforme standard d'orchestration de conteneurs" },
    description: {
      en: "Declarative container management with automated rollouts, service mesh, and self-healing.",
      fr: "Gestion déclarative de conteneurs avec déploiements automatisés, maillage de services et auto-réparation.",
    },
    badgeColor: "bg-blue-600/10 text-blue-700 border-blue-300 dark:border-blue-700 dark:text-blue-400",
    accentColor: "#2563eb",
    iconName: "Layers",
    roleInArchitecture: "High-density container orchestration platform managing microservice pods.",
    defaultDeploymentZone: "Compute / VPC Cluster",
    supportedProtocols: ["HTTPS / REST", "gRPC", "TCP / Connection Pool"],
    typicalOutboundTo: ["database", "cache", "messaging"],
    bestFor: ["Large engineering teams", "Complex microservices", "Multi-region deployments"],
    pricingModel: "Open Source",
    documentationUrl: "https://kubernetes.io",
  },

  // --- CI/CD & DEVOPS ---
  {
    id: "github_actions",
    name: "GitHub Actions",
    category: "cicd",
    tier: "infrastructure",
    tagline: {
      en: "Automated CI/CD workflows in your GitHub repository",
      fr: "Workflows CI/CD automatisés dans votre dépôt GitHub",
    },
    description: {
      en: "Build, test, and deploy code directly from GitHub pull requests and releases.",
      fr: "Compilez, testez et déployez du code directement depuis les pull requests et releases GitHub.",
    },
    badgeColor: "bg-slate-600/10 text-slate-800 border-slate-300 dark:border-slate-700 dark:text-slate-300",
    accentColor: "#1e293b",
    iconName: "GitBranch",
    roleInArchitecture: "Automated test runner and deployment pipeline triggered on code commits.",
    defaultDeploymentZone: "DevOps & CI/CD Pipeline",
    supportedProtocols: ["HTTPS / REST"],
    typicalOutboundTo: ["deployment"],
    bestFor: ["Automated testing", "Continuous deployment", "Security scanning"],
    pricingModel: "Freemium",
    documentationUrl: "https://github.com/features/actions",
  },
  {
    id: "docker",
    name: "Docker",
    category: "cicd",
    tier: "infrastructure",
    tagline: { en: "Universal container packaging standard", fr: "Standard universel d'empaquetage de conteneurs" },
    description: {
      en: "Standardized container packaging guaranteeing identical behavior from dev to production.",
      fr: "Empaquetage de conteneurs standardisé garantissant un comportement identique du développement à la production.",
    },
    badgeColor: "bg-sky-500/10 text-sky-600 border-sky-200 dark:border-sky-800 dark:text-sky-400",
    accentColor: "#0ea5e9",
    iconName: "Box",
    roleInArchitecture: "Container image packaging standard used across development and cloud hosts.",
    defaultDeploymentZone: "DevOps & CI/CD Pipeline",
    supportedProtocols: [],
    typicalOutboundTo: ["deployment"],
    bestFor: ["Reproducible builds", "Local development parity", "Microservice packaging"],
    pricingModel: "Open Source",
    documentationUrl: "https://www.docker.com",
  },

  // --- COMMUNICATIONS ---
  {
    id: "resend",
    name: "Resend",
    category: "communication",
    tier: "external",
    tagline: {
      en: "Modern transactional email API for developers",
      fr: "API d'email transactionnel moderne pour développeurs",
    },
    description: {
      en: "React-email templates, high deliverability, domain authentication, and fast API.",
      fr: "Modèles React-email, haute délivrabilité, authentification de domaine et API rapide.",
    },
    badgeColor: "bg-stone-600/10 text-stone-800 border-stone-300 dark:border-stone-700 dark:text-stone-300",
    accentColor: "#292524",
    iconName: "Mail",
    roleInArchitecture: "Transactional email delivery service for magic links, receipts, and user notifications.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["HTTPS / REST"],
    typicalOutboundTo: [],
    bestFor: ["Transactional emails", "React Email templates", "Modern SaaS apps"],
    pricingModel: "Freemium",
    documentationUrl: "https://resend.com",
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "communication",
    tier: "external",
    tagline: {
      en: "SMS, WhatsApp, Voice, and Verification API",
      fr: "API SMS, WhatsApp, Voix et Vérification",
    },
    description: {
      en: "Programmable messaging, 2FA SMS one-time-passcodes, and telephony infrastructure.",
      fr: "Messagerie programmable, codes OTP SMS pour la double authentification et infrastructure de téléphonie.",
    },
    badgeColor: "bg-red-500/10 text-red-600 border-red-200 dark:border-red-800 dark:text-red-400",
    accentColor: "#ef4444",
    iconName: "Phone",
    roleInArchitecture: "Telephony gateway delivering SMS verifications and customer text notifications.",
    defaultDeploymentZone: "External SaaS / APIs",
    supportedProtocols: ["HTTPS / REST", "Webhook (HTTPS POST)"],
    typicalOutboundTo: ["backend"],
    bestFor: ["SMS OTP verification", "Customer messaging", "Voice integration"],
    pricingModel: "Managed SaaS",
    documentationUrl: "https://www.twilio.com",
  },
];

export const TECH_BY_ID = new Map<string, Technology>(
  TECH_CATALOG.map((tech) => [tech.id, tech])
);
