import { StackPreset } from "../types";

export const STACK_PRESETS: StackPreset[] = [
  {
    id: "modern_ai_saas",
    name: "Modern AI SaaS Platform",
    badge: "Popular AI Stack",
    projectType: "ai_app",
    description: "Full-stack AI SaaS with RAG embeddings, subscription billing, and multi-tenant authentication.",
    techIds: [
      "nextjs",
      "fastapi",
      "postgresql",
      "redis",
      "clerk",
      "stripe",
      "gemini",
      "pinecone",
      "s3",
      "vercel",
      "gcp_cloudrun",
      "sentry",
      "github_actions",
    ],
    highlights: [
      "FastAPI orchestrates Gemini 3.0 reasoning & Pinecone vector search",
      "Next.js frontend with Clerk organization auth",
      "Stripe recurring subscription webhooks",
      "Hybrid Vercel + Cloud Run serverless deployment",
    ],
  },
  {
    id: "scalable_mobile_app",
    name: "Cross-Platform Mobile App",
    badge: "Mobile & Backend",
    projectType: "mobile",
    description: "Production mobile architecture for iOS and Android with realtime push, fast APIs, and cloud media.",
    techIds: [
      "reactnative",
      "nestjs",
      "postgresql",
      "redis",
      "firebase_auth",
      "stripe",
      "s3",
      "resend",
      "sentry",
      "gcp_cloudrun",
      "github_actions",
    ],
    highlights: [
      "React Native (Expo) client with biometric/social auth",
      "NestJS enterprise TypeScript modular backend",
      "PostgreSQL primary data store with Redis query cache",
      "S3 presigned URLs for client media uploads",
    ],
  },
  {
    id: "high_perf_ecommerce",
    name: "High-Traffic E-Commerce",
    badge: "E-Commerce",
    projectType: "ecommerce",
    description: "Speed-optimized shopping platform with instant search, inventory transactions, and payment webhooks.",
    techIds: [
      "nextjs",
      "django",
      "postgresql",
      "redis",
      "stripe",
      "algolia",
      "cloudflare_r2",
      "resend",
      "sentry",
      "aws_ecs",
      "github_actions",
    ],
    highlights: [
      "Next.js storefront with sub-50ms Algolia search",
      "Django REST framework managing transactional orders",
      "Cloudflare R2 zero-egress product image storage",
      "Stripe checkout sessions and automated tax handling",
    ],
  },
  {
    id: "lean_solo_founder",
    name: "Lean Solo Founder Stack",
    badge: "Maximum Velocity",
    projectType: "saas",
    description: "Minimal complexity stack with zero maintenance serverless tools for solo developers.",
    techIds: [
      "sveltekit",
      "supabase_db",
      "supabase_auth",
      "lemonsqueezy",
      "cloudflare_r2",
      "resend",
      "vercel",
      "github_actions",
    ],
    highlights: [
      "SvelteKit fullstack with Supabase PostgreSQL + Auth RLS",
      "Lemon Squeezy merchant of record (handles global VAT/tax)",
      "Zero devops: deployed on Vercel Edge with Cloudflare R2",
    ],
  },
  {
    id: "realtime_collab",
    name: "Real-Time Collaborative Tool",
    badge: "Low Latency",
    projectType: "realtime",
    description: "High-concurrency platform with WebSockets, in-memory state sync, and fast Go microservices.",
    techIds: [
      "react",
      "gin",
      "postgresql",
      "redis_db",
      "auth0",
      "rabbitmq",
      "sentry",
      "datadog",
      "gcp_cloudrun",
    ],
    highlights: [
      "Go (Gin) compiled microservice handling WebSocket connections",
      "Redis in-memory real-time state synchronization",
      "RabbitMQ event bus for heavy async export jobs",
    ],
  },
  {
    id: "enterprise_microservices",
    name: "Enterprise Event-Driven Microservices",
    badge: "High Scale",
    projectType: "microservices",
    description: "Decoupled enterprise architecture with Apache Kafka event streaming and Kubernetes pod orchestration.",
    techIds: [
      "react",
      "springboot",
      "postgresql",
      "mongodb",
      "kafka",
      "keycloak",
      "datadog",
      "docker",
      "kubernetes",
    ],
    highlights: [
      "Spring Boot microservices communicating via Kafka event log",
      "Polyglot persistence: PostgreSQL for ACID + MongoDB for documents",
      "Keycloak enterprise SSO / SAML authentication",
      "Kubernetes container orchestration with Datadog APM tracing",
    ],
  },
];
